apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-qbi9w4roawdxh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-qbi9w4roawdxh
    app.kubernetes.io/part-of: test-gitlabrenovate-m85adg9fy9axi
  name: component-qbi9w4roawdxh
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-qbi9w4roawdxh
status:
  loadBalancer: {}
